### PR TITLE
Add support to RETURNING clause

### PR DESCRIPTION
**Pull request by xulien**
This PR contains a commit about my previous PR on adapters https://github.com/prest/prest/issues/50,
sorry for the all in one

### CODE REVIEW

**Review by felipeweb — CHANGES_REQUESTED** [review]
@xulien some tests are broken. could you check? i guess it is just fix permissions on https://github.com/prest/controllers/blob/master/testdata/prest.toml

**Comment by felipeweb** [comment]
@xulien these 2 tests are broken: `execute select in a table with select *` and `execute select in a table with select * and distinct`

**Comment by xulien** [comment]
the broken tests are the ones I added, I added the return value test, but I'm not sure it's relevant. I'm trying to better understand the purpose of this test suite.

**Comment by xulien** [comment]
Okay, I found the prest.toml in testdata... I didn't have the same errors in the tests...

So the problem for the error tests you found felipe, comes from the FieldsPermissions function in adapt/postgresql.go. The test requests all columns via wildcard, and the rights explicitly allow the select on "id,name,cellphone", i.e. all columns, but wildcard is not equal to "id,name,cellphone"... hence the rejection.
So either we consider that with the restrictions we cannot use the wildcard, and the fields must be explicitly in the url, or in case of wildcard, we will have to add in the FieldsPermissions function, a request on the requested table to get the list of columns and compare it to the one described in the conf file.

since I'm lazy, I'd prefer the first option...

**Comment by xulien** [comment]
As I mentioned earlier, I am not a golang dev _not yet, it's in my todolist_, that's why what follows, I say with great caution and humility: but the division into modules, here seems to me to complicate things unnecessarily. In any case Adapter and Controllers, seems to me too intertwined. For example, the _select problem that was no longer working could not be detected. Just like this problem on FieldsPermissions, the tests in the Adapter module are good, but the problem is raised by the Controllers module tests, which are not necessarily executed ?!

Again, I'm not a dev golang, there may be an excellent reason, but then it seems to me there's a problem with the tests.

**Comment by felipeweb** [comment]
@xulien we just check status on tests so have some wrong.
you can use fmt.Println to debug on travis and remove prints after debug

**Comment by xulien** [comment]
@felipeweb  hi, any news regarding a decision for the wildcard problem in permissions management? Otherwise I would simply remove the blocking test, and adapt the documentation accordingly.

**Pull request closed without merging**
