### PR TITLE
wrapper names with "

### PR DESCRIPTION
**Pull request by felipeweb**
https://github.com/prest/prest/issues/200 depends on https://github.com/prest/statements/pull/1 and https://github.com/prest/adapters/pull/8

### CODE REVIEW

**Review by crgimenes — APPROVED** [review]
LGTM

**Review by marioidival — APPROVED** [review]
LGTM

**Comment by felipeweb** [comment]
just closing and reopen for tests

**Comment by avelino** [comment]
@felipeweb on travis-ci rebuild option
screenshot 2017-08-09 11 15 26

**Review by crgimenes — CHANGES_REQUESTED** [review]
Remove the "poor men debug" aka printf(">>>>...

**Pull request merged**
